### ISSUE TITLE
Architect's Bench rejects Tinker's Construct seared stone and seared brick

### ISSUE THREAD

**Issue by okid0kii** [TridentMC/ArchitectureCraft#24]
Hello.
Can you add compatibility with blocks of Tinker'š construct?

**Comment by falkreon** [comment]
For most blocks, that compatibility is already there. I just went and verified that Knightslime and Manyullyn are working. I suspect all the rest of the material blocks - pig iron, ardite, etc. - work. The problem here is the seared stone. In spite of the fact that the tooltip says "safe for crafting," it's really not; each seared stone and seared brick block is a tileEntity, and I think ArchitectureCraft is doing the right thing in rejecting unknown blocks with custom models and arbitrary NBT.

I think this could happen though. It comes down to special-casing seared stone and seared brick varieties, which isn't worse than any of the other mod compat so far.
