### ISSUE TITLE
Fancy balustrade creates severe lag

### ISSUE THREAD

**Issue by UnixRonin** [TridentMC/ArchitectureCraft#32]
architecturecraft-1.12-2.68
forge-1.12.2-14.23.2.2654

This is another issue inherited from GregT's original mod.

In short:  The fancy balustrade creates severe lag within a sizeable area (seems to affect an area of most of a chunk horizontally and maybe as much as 8-10 blocks vertically).  My best guess at what APPEARS to be going on is that placing or breaking any block within the affected area causes a lighting recalculation, and the lighting recalculation on the fancy railings seems to be extremely expensive, probably because of the complex curved surfaces.

I don't know whether this is actually fixable or not.

**Comment by freelancerleno** [comment]
I can confirm. Tested without any other mod.

Huge lags spikes when placing or break any block near fancy balustrades (when balustrades are loaded by the player).
It also appears less strongly with normal balustrade or other blocks of the mod but more block must be present to have the same kind of lag.
Disable the fancy lighting reduce lag spikes.

**Comment by chaos234** [comment]
Confirmed on my server to. This **must be resolved**, because I need these for my building but with such kinds of lags it is horrible.

@freelancerleno - WHere to disable fancy lightning? My config is empty which means either a bug for constructing the config or this config option is missing.

However, simply truncate that shit for lighting out because who needs it? Blocks are for design and not for lighting or should they glow like glowstone? Simply make the modles and that's it, without any lag spikes (hopefully)

**Comment by UnixRonin** [comment]
Hmmmm.......      Actually, I haven't tried this with railings and have no plans to, but if you craft spheres or quarter spheres from glowstone or jack-o'lanterns, they do indeed glow.  I see no reason railings wouldn't too.
And yeah, that math sounds bad...

**Comment by chaos234** [comment]
What I don't get is the fact that this issiue is open since April and not even a Member nor any Contributor has responded here.

Sorry, but since this is a game breaking issue it should be handled as critical ones because you want to build them cause you need them while they are looking fine but then you are getting those shitty lags ... horrible that this isn't resolved yet.

**Comment by freelancerleno** [comment]
@chaos234  Fancy lighting is a Minecraft thing, in the graphical menu. Disabling it will make Minecraft lighting "square".

Unfortunately, and from what I noticed. Minecraft (I specify in modded) becomes more and more buggy as and when versions come out.

I will therefore tend to say that this problem comes from Minecraft itself.

I am not a coder in Java but a level designer on graphic engines like Source and Unreal to name just a few. The light, especially if it is not calculated in advance (like dynamics lights) if it is poorly made, it can have a very big impact if a model or a moving decort (like placing or destroying a block in MC recalculates the shadows on complex models, terrain, ...).
That's it, I imagine the problem here.
I hope that the 1.13 will improve things with the mods and above all, not content with a banal addition of content, which honestly, can largely be done with mods ...

Sorry for my english, I'm french;)

**Comment by chaos234** [comment]
Not the problem :) - After all such decorativ blocks are only modles with a special design and as long as they do not any ligthing like glowstone or what ever else, they shouldn't be affected that horrible over fancy lighting.

I blame the math and java for it after all but would this game not be written in java we wouldn't have even one mod cause who want's to learn c#/c++?

After all we can only try to fix stupied MC code over ASM then even then if it's a bit evil :D

**Comment by UnixRonin** [comment]
Minecraft's lighting code seems to be generally a problem.  But to be fair, real dynamic lighting is hard.

**Comment by falkreon** [comment]
> What I don't get is the fact that this issiue is open since April and not even a Member nor any Contributor has responded here.
> 
> Sorry, but since this is a game breaking issue it should be handled as critical ones because you want to build them cause you need them while they are looking fine but then you are getting those shitty lags ... horrible that this isn't resolved yet.

I'm not the dev for this, but I'm the main dev on Mirage, so I'm no stranger to lighting :) Let's just do a quick dive into minecraft lighting to kind of contain all this speculation:

Lighting a chunk in Minecraft, to simplify it, is about zeroing out its lightmap and flooding in lights from inside it and from the neighboring chunks. The result is two light values in each block, one from the sky and one from artificial light. In this case the one that tends to lag hard is the skylight, even though the non-sky floodfill is ~O(n^3), because when a block is placed or broken to trigger it, you need to scan all the way down till you find a new top block, so it's ~O(n^2) for large n. You'll see this at work if you try to worldedit in a roof at height limit over a large area, and it's also why mojang has repeatedly told us "no more world height".

"Good" dynamic lighting (which Minecraft doesn't have) is shadowing instead: Make a black-and-white texture paired with a depth buffer. Move the camera to a light's position. Render whatever casts shadows into this texture at low detail. Then when you do the regular rendering from your regular camera location, do some Fancy Trigonometry to transform the pixel's location from camera space to shadow-camera space. Then anything that passes a depth test is lit, so it gets drawn at an opacity dependant on its new Z value, which tells you how far it is from the light. This has a whole bunch of problems like sparkling or blocky shadows that good engines have a million neat tricks to mitigate. Anyhow, repeat for each light in the scene, and shadowtree rebakes can be extremely deferred.

**Comment by falkreon** [comment]
Rebaking chunks in Minecraft - which, I've used fancy balustrades on my old dev potato and never had a problem, but if you're experiencing issues on breaking and placing, here's where you look: The block geometry is recalculated in that 16x16x16 area. The only exception is Chisels & Bits. I bet you could get the game to lag out really hard just by putting a redstone clock in that chunk. I *really don't* like ArchitectureCraft's original model format, and I suspect stepping up to an actual .obj file (or two .obj files) even at the same poly count would cause the issue to evaporate.

**Comment by exaskye** [comment]
> What I don't get is the fact that this issiue is open since April and not even a Member nor any Contributor has responded here.

Something to keep in mind Elytra is not really a team per-se, as it is a way for all of us to share infrastructure, code, a discussion space, and have a bit of cross-promotion. Each project here still has a specific owner and maintainer, and generally we avoid stepping into issues on repos that are not owned by ourselves unless they are very simple issues. (or, meta organizational issues, hence my response here.)

Darkevilmac has been on a bit of a hiatus lately, and so all of the repos belonging to him have kind of stagnated, despite the fact other Elytra projects are still active. If Darkevilmac were to explicitly ask another Elytra member to take over his projects, be it temporarily or permanently, then this would change; but, either way, right now most Elytra members with the experience required to maintain his fairly complex projects are busy with non-Minecraft matters.

We see your issues, and we're reading them, but the fact of the matter is *this is not our project* and *we have not been given permission to act on Darkevilmac's behalf*.

**Comment by UnixRonin** [comment]
**Totally** understand that, @unascribed.

**Comment by darkevilmac** [comment]
I am on a bit of a hiatus, if anyone in elytra wants to work on any of my mods then just email me. I'm fine with changes being made as I'd be looking over commits anyways.

I've just been too busy with work and a non-minecraft related hobby to spend much time on any of my mods.

I still plan on updating to 1.13 and stuff but other than that I just don't have enough time for this stuff at the moment.
