### ISSUE TITLE
Glitched Models

### ISSUE THREAD

**Issue by Hellcode48** [TridentMC/ArchitectureCraft#73]
- 3.95
- 1.12.2
- 14.23.5.2838
- There is none (no errors in log)

![2019-07-24_22 01 46](https://user-images.githubusercontent.com/4357903/61847212-af235d00-ae5e-11e9-8c7c-38a8a860fdd6.png)

**Comment by darkevilmac** [comment]
What's the issue here exactly?

**Comment by Hellcode48** [comment]
As you can see in the image the bannister and end piece is glitched, seemed to have happened after I updated to the latest update you posted. Breaking and placing does not fix the problem.

**Comment by darkevilmac** [comment]
The title for the issue says there's an issue with the textures. I'm not really seeing any problems with the textures, if you're talking about the models could you send a before and after from pre and post update as I'm having trouble understanding what exactly is wrong.

**Comment by Hellcode48** [comment]
Ahh sorry, yes the models are not correct with hitboxes

**Comment by Hellcode48** [comment]
@darkevilmac Hopefully you can fix the models, very odd. You should totally add walls and fence gates.

**Comment by Mystara0001** [comment]
I just ran into this issue, let me see if I can clarify it a little bit more. Bannisters that should be along the side of the stairs are appearing in the center of the stairs. Their hit boxes are in the correct place however.

So if I build a step and try to put a bannister on it, it appears to be in the very center of the stair instead of along the edge.

The original picture isn't very useful because it mixes railings and bannisters. But you can see on the stairs (not around them) that the bannister is centered instead of on the side.

**Comment by Hellcode48** [comment]
Agreed, mainly the reason I used that picture is because the railing end is also messed up (the hitbox is correct though).

**Comment by darkevilmac** [comment]
@Mystara0001 Thanks for the clarification, I'm currently out of my house but I'll take a look at this as soon as I can.
